# apiVersion: v1
#kind: ConfigMap
#metadata:
  #name: frontend
  #namespace: expense
#data:
  #DB_HOST: mysql # mysql component service name
  #DB_HOST: db-dev.devops91.cloud
---
kind: Deployment
apiVersion: webs/v1
metadata:
  name: frontend
  namespace: expense
  # these labels are deployment related labels
  labels:
    component: frontend
    project: expense
    tier: web
spec:
  replicas: 2
  selector:
    matchLabels:
      component: frontend
      project: expense
      tier: web
  # pod definition
  template:
    metadata:
      labels:
        component: frontend
        project: expense
        tier: web
    spec:
      containers:
      - name: frontend
        image: sandeepnainala9/frontend:v1.0
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: expense
spec:
  type: LoadBalancer
  selector:
    component: frontend
    project: expense
    tier: web
  ports:
  - protocol: TCP
    port: 8080 #service-port
    targetPort: 8080 #target-port